polls/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

app_name = "polls"

router = routers.DefaultRouter()
router.register(r'result', views.PollsViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls), name='api_polls'),
    url(r'^$', views.index, name="index"),
    url(r'^vote$', views.voting, name="voting"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    # url(r'^api/polls$', views.polls_dashboard_api, name="api_polls"),
]

pomelo_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"", include('polls.urls'))
]

polls/models.py
from django.db import models


class Polls(models.Model):
    party = models.CharField(max_length=100, default=None, null=True, blank=True)
    vote_count = models.IntegerField(default=0)

    def __str__(self):return self.party

polls/forms.py
from django import forms
from .models import Polls


class PollsForm(forms.ModelForm):
    parties = [('DOCKER', 'DOCKER'),
               ('PYTHON', 'PYTHON'),
               ('CIRCLECI', 'CIRCLECI'),
               ('KUBERNETES', 'KUBERNETES')]
    party = forms.CharField(widget=forms.Select(choices=parties), required=True)

    class Meta:
        model = Polls
        exclude = ['vote_count']

polls/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.http import JsonResponse
from .models import Polls
from .forms import PollsForm
import json
import logging
from rest_framework import viewsets
from .serializers import PollsSerializer


logger = logging.getLogger(__name__)


def index(request):
    return render(request=request, template_name="base.html")


def voting(request):
    poll_form = PollsForm(request.POST or None)
    if poll_form.is_valid():
        poll, _ = Polls.objects.get_or_create(party=poll_form.cleaned_data.get("party"))
        poll.vote_count += 1
        poll.save()
        return redirect("polls:dashboard")
    return render(request=request, template_name='generic_form.html', context={'form': poll_form})


def dashboard(request):
    polls_data = Polls.objects.all().values('party', 'vote_count')
    return render(request=request, template_name="dashboard.html",
                  context={'entries': polls_data, 'headings': ["Party", "Vote"]})


# def polls_dashboard_api(request):
#     polls_data = Polls.objects.all().values('party', 'vote_count')
#     return JsonResponse(data={"polls": json.dumps(list(polls_data))})


class PollsViewSet(viewsets.ModelViewSet):
    queryset = Polls.objects.all()
    serializer_class = PollsSerializer

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Hi Loaddy</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="{% url 'polls:index' %}">Online Voting</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'polls:voting' %}">Vote</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'polls:dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="api/result">API</a>
                  </li>
                </ul>
              </div>
        </nav>
    {% endblock %}


    {% block body %}
        <h1 style="text-align: center; margin: 2%">Welcome</h1>
        <div class="container" style="margin-left: 30%">
                <img src="{% static 'img/homepage_vote.jpg' %}" alt="">
        </div>
    {% endblock %}

    <footer class="footer">
            <div class="container" style="text-align: center">
                <span style="color: white">© ashishsr</span>
            </div>
    </footer>
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block body %}
    <div class="container" style="margin: 10%">
      <div class="row">

      <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                {% for heading in headings %}
                    <th scope="col">
                        {{ heading }}
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for entry in entries  %}
                <tr>
{#                    <th scope="row"></th>#}
                    <td> {{ entry.party}} </td>
                    <td> {{ entry.vote_count }} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

      </div>
    </div>

{% endblock %}

templates/forms.html
{% for field in form %}
    <div>
        <div>{{ field.label }}</div>
        <div>{{ field }}</div>
    </div>
{% endfor %}

templates/generic_form.html
{% extends 'base.html' %}
{% block body %}
    <div class="container" style="position: fixed; top: 40%; left: 42%;">
        <form class="form-inline" action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label class="my-1 mr-2" for="">{{ field.label_tag }}</label>
                    <div>{{ field }}</div>
                </div>
            {% endfor %}
            <button class="btn btn-primary my-1" type="submit" style="margin: 2%">Vote</button>
        </form>
    </div>
{% endblock %}